"""add drive integration

Revision ID: 157373eb45c8
Revises: a1b2c3d4e5f6
Create Date: 2026-02-15 18:44:30.649210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157373eb45c8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_drive_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('content_snippet', sa.Text(), nullable=True),
    sa.Column('modified_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('web_view_link', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_drive_files_company_id'), 'monitored_drive_files', ['company_id'], unique=False)
    op.create_index(op.f('ix_monitored_drive_files_file_id'), 'monitored_drive_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_monitored_drive_files_processed'), 'monitored_drive_files', ['processed'], unique=False)
    with op.batch_alter_table('detected_software') as batch_op:
        batch_op.add_column(sa.Column('source_drive_file_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_detected_software_drive_file', 'monitored_drive_files', ['source_drive_file_id'], ['id'])
    op.add_column('email_integrations', sa.Column('drive_sync_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('email_integrations', sa.Column('drive_last_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('email_integrations', sa.Column('drive_page_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_integrations', 'drive_page_token')
    op.drop_column('email_integrations', 'drive_last_sync_at')
    op.drop_column('email_integrations', 'drive_sync_enabled')
    with op.batch_alter_table('detected_software') as batch_op:
        batch_op.drop_constraint('fk_detected_software_drive_file', type_='foreignkey')
        batch_op.drop_column('source_drive_file_id')
    op.drop_index(op.f('ix_monitored_drive_files_processed'), table_name='monitored_drive_files')
    op.drop_index(op.f('ix_monitored_drive_files_file_id'), table_name='monitored_drive_files')
    op.drop_index(op.f('ix_monitored_drive_files_company_id'), table_name='monitored_drive_files')
    op.drop_table('monitored_drive_files')
    # ### end Alembic commands ###
