"""add_category_direction_to_monitored_emails

Revision ID: 32a21f642c94
Revises: 661e53a35a97
Create Date: 2026-02-11 00:45:14.128852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a21f642c94'
down_revision: Union[str, None] = '661e53a35a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_emails', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('monitored_emails', sa.Column('direction', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitored_emails', 'direction')
    op.drop_column('monitored_emails', 'category')
    # ### end Alembic commands ###
