"""add jira_webhooks table

Revision ID: 506e26659117
Revises: 9ce999d56cc9
Create Date: 2026-02-13 17:28:59.079367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506e26659117'
down_revision: Union[str, None] = '9ce999d56cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_webhooks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('webhook_secret', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('events_received', sa.Integer(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_webhooks_company_id'), 'jira_webhooks', ['company_id'], unique=True)
    op.create_index(op.f('ix_jira_webhooks_webhook_secret'), 'jira_webhooks', ['webhook_secret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jira_webhooks_webhook_secret'), table_name='jira_webhooks')
    op.drop_index(op.f('ix_jira_webhooks_company_id'), table_name='jira_webhooks')
    op.drop_table('jira_webhooks')
    # ### end Alembic commands ###
