"""add jira polling

Revision ID: 51f794900729
Revises: 157373eb45c8
Create Date: 2026-02-15 20:48:45.046395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f794900729'
down_revision: Union[str, None] = '157373eb45c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_polling_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('jql_filter', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issues_synced', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_polling_configs_company_id'), 'jira_polling_configs', ['company_id'], unique=True)
    op.create_table('monitored_jira_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('issue_key', sa.String(length=50), nullable=False),
    sa.Column('project_key', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description_snippet', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('reporter', sa.String(length=255), nullable=True),
    sa.Column('issue_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('web_url', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_jira_issues_company_id'), 'monitored_jira_issues', ['company_id'], unique=False)
    op.create_index(op.f('ix_monitored_jira_issues_issue_key'), 'monitored_jira_issues', ['issue_key'], unique=False)
    op.create_index(op.f('ix_monitored_jira_issues_processed'), 'monitored_jira_issues', ['processed'], unique=False)
    with op.batch_alter_table('detected_software') as batch_op:
        batch_op.add_column(sa.Column('source_jira_issue_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_detected_software_jira_issue', 'monitored_jira_issues', ['source_jira_issue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detected_software') as batch_op:
        batch_op.drop_constraint('fk_detected_software_jira_issue', type_='foreignkey')
        batch_op.drop_column('source_jira_issue_id')
    op.drop_index(op.f('ix_monitored_jira_issues_processed'), table_name='monitored_jira_issues')
    op.drop_index(op.f('ix_monitored_jira_issues_issue_key'), table_name='monitored_jira_issues')
    op.drop_index(op.f('ix_monitored_jira_issues_company_id'), table_name='monitored_jira_issues')
    op.drop_table('monitored_jira_issues')
    op.drop_index(op.f('ix_jira_polling_configs_company_id'), table_name='jira_polling_configs')
    op.drop_table('jira_polling_configs')
    # ### end Alembic commands ###
