"""add signal events health scores review drafts tables

Revision ID: 92925b376387
Revises: cb650f655c22
Create Date: 2026-02-10 01:00:39.841851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92925b376387'
down_revision: Union[str, None] = 'cb650f655c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('software_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('category_breakdown', sa.JSON(), nullable=False),
    sa.Column('signal_summary', sa.Text(), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('scoring_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scoring_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_scores_company_id'), 'health_scores', ['company_id'], unique=False)
    op.create_index(op.f('ix_health_scores_software_id'), 'health_scores', ['software_id'], unique=False)
    op.create_table('signal_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('software_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=500), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_events_company_id'), 'signal_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_signal_events_occurred_at'), 'signal_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_signal_events_software_id'), 'signal_events', ['software_id'], unique=False)
    op.create_table('review_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('software_id', sa.Uuid(), nullable=False),
    sa.Column('health_score_id', sa.Uuid(), nullable=True),
    sa.Column('draft_subject', sa.String(length=500), nullable=True),
    sa.Column('draft_body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('edited_body', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['health_score_id'], ['health_scores.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_drafts_company_id'), 'review_drafts', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_drafts_company_id'), table_name='review_drafts')
    op.drop_table('review_drafts')
    op.drop_index(op.f('ix_signal_events_software_id'), table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_occurred_at'), table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_company_id'), table_name='signal_events')
    op.drop_table('signal_events')
    op.drop_index(op.f('ix_health_scores_software_id'), table_name='health_scores')
    op.drop_index(op.f('ix_health_scores_company_id'), table_name='health_scores')
    op.drop_table('health_scores')
    # ### end Alembic commands ###
