"""add intelligence_cache table

Revision ID: bafe77575200
Revises: ccb8eab5b525
Create Date: 2026-02-11 02:02:30.135716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafe77575200'
down_revision: Union[str, None] = 'ccb8eab5b525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('software_name', sa.String(length=255), nullable=False),
    sa.Column('auto_category', sa.String(length=100), nullable=True),
    sa.Column('avg_health_score', sa.Integer(), nullable=True),
    sa.Column('company_count', sa.Integer(), nullable=False),
    sa.Column('industry_distribution', sa.JSON(), nullable=True),
    sa.Column('size_distribution', sa.JSON(), nullable=True),
    sa.Column('cuj_data', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_name', 'software_name')
    )
    op.create_index(op.f('ix_intelligence_cache_software_name'), 'intelligence_cache', ['software_name'], unique=False)
    op.create_index(op.f('ix_intelligence_cache_vendor_name'), 'intelligence_cache', ['vendor_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_cache_vendor_name'), table_name='intelligence_cache')
    op.drop_index(op.f('ix_intelligence_cache_software_name'), table_name='intelligence_cache')
    op.drop_table('intelligence_cache')
    # ### end Alembic commands ###
