"""add software registrations table

Revision ID: cb650f655c22
Revises: da6d144d0280
Create Date: 2026-02-10 00:46:14.723846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb650f655c22'
down_revision: Union[str, None] = 'da6d144d0280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('software_name', sa.String(length=255), nullable=False),
    sa.Column('intended_use', sa.Text(), nullable=True),
    sa.Column('jira_workspace', sa.String(length=255), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('pagerduty_service', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detection_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['detection_id'], ['detected_software.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'vendor_name', 'software_name')
    )
    op.create_index(op.f('ix_software_registrations_company_id'), 'software_registrations', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_software_registrations_company_id'), table_name='software_registrations')
    op.drop_table('software_registrations')
    # ### end Alembic commands ###
