"""add confidence_tier to health_scores and review_drafts

Revision ID: ccb8eab5b525
Revises: 32a21f642c94
Create Date: 2026-02-11 01:23:32.844785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb8eab5b525'
down_revision: Union[str, None] = '32a21f642c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_scores', sa.Column('confidence_tier', sa.String(length=20), nullable=False, server_default='preliminary'))
    op.add_column('review_drafts', sa.Column('confidence_tier', sa.String(length=20), nullable=False, server_default='preliminary'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_drafts', 'confidence_tier')
    op.drop_column('health_scores', 'confidence_tier')
    # ### end Alembic commands ###
